name: Deploy to Azure Blob Storage

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload static site to Azure
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch \
              --account-name raduweb \
              --auth-mode key \
              --destination '$web' \
              --source . \
              --account-key ${{ secrets.AZURE_STORAGE_KEY }}
